name: DevSecOps Pipeline
on: [push]
    branches: 
      - [ test ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: pwcindiadevopsteam/base-container-image:sha256-c9081feb9227ced18a489193bda87c920c43649f6a110c1e05ab83575e252a08.sig
    permissions:
      security-events: write
      id-token: write
      contents: read
      attestations: write
      packages: write
      
    
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

