# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: 
  push:
    branches: 
      - test
  
#  release:
#    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pwcindiadevopsteam/base-container-image:sha256-c9081feb9227ced18a489193bda87c920c43649f6a110c1e05ab83575e252a08.sig
      credentials:
        username: pwcindiadevopsteam/${{ github.actor }}
        password: ${{ secrets.github_token }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
#    - name: Set up JDK 11
#      uses: actions/setup-java@v4
#      with:
#        java-version: '11'
#        distribution: 'temurin'
#        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#        settings-path: ${{ github.workspace }} # location for the settings.xml file

#    - name: Build with Maven
#      run: mvn -B package --file pom.xml

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
