# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: 
  push:
    branches: 
      - test
  
#  release:
#    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pwcindiadevopsteam/base-container-image:main
      #image: ghcr.io/pwcindiadevopsteam/base-container-image:sha256-c9081feb9227ced18a489193bda87c920c43649f6a110c1e05ab83575e252a08
      credentials:
        username: pwcindiadevopsteam/${{ github.actor }}
        password: ${{ secrets.github_token }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
#    - name: Build with Maven Wrapper
#      run: mvn -B package --file pom.xml
#      run: |
#           chmod +x ./build/build_maven.sh
#           set -x 
#           ./build/build_maven.sh
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v4
      with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2   

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build and analyze
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dmaven.test.skip=true -Dcheckstyle.skip  -Dsonar.projectKey=software-supply-chain-demo -Dsonar.projectName='software-supply-chain-demo'
#-Pcoverage
      env:
          # Needed to get some information about the pull request, if any
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
        SONAR_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn clean package --file pom.xml -Dmaven.test.skip=true -Dcheckstyle.skip
    
    #- name: SonarCloud Scan
    #  uses: sonarsource/sonarcloud-github-action@v3.1.0
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -Dmaven.test.skip=true -Dcheckstyle.skip
      env:
        GITHUB_TOKEN: ${{ github.token }}
